# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-06-30 10:25
from __future__ import unicode_literals

from django.db import migrations, models
import django_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ios_notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apnservice',
            name='passphrase',
            field=django_fields.fields.EncryptedCharField(blank=True, block_type=b'MODE_CBC', help_text=b'Passphrase for the private key', max_length=142, null=True
),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.CharField(blank=True, help_text=b'Alert message to display to the user. Leave empty if no alert should be displayed to the user.', max_length=2048),                                                                             
        ),
    ]
