# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-04-23 20:48


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ios_notifications', '0002_auto_20170630_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='title',
            field=models.CharField(blank=True, help_text=b'Title to display to the user. Leave empty if no title should be displayed to the user.', max_length=240),
        ),
    ]
